version: "2"
services:
  nginx-php:
    container_name: nginx-php
    image: alicfeng/nginx-php-supervisor:php.7.1.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./srv/nginx/nginx.conf/:/usr/local/nginx/nginx.conf:ro
      - ./srv/php/php-fpm.conf/:/usr/local/php/etc/php-fpm.conf:ro
      - ./srv/php/php.ini-production:/usr/local/php/lib/php.ini:ro
      - ./srv/nginx/conf.d:/usr/local/nginx/conf.d
      - /www/api.yi-insurance.com:/www/api.yi-insurance.com
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./srv/mysql/config/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123!@#qwe
      MYSQL_USER: tsb
      MYSQL_PASSWORD: 123!@#qwe
      MYSQL_DATABASE: tsb_dev
    restart: always
    
  redis:
    container_name: redis
    image: redis:4.0.12
    command: ["redis-server", "/etc/redis/redis.conf","--protected-mode","no","--appendonly", "yes"]
    ports:
      - 6388:6388
    volumes:
      - /data/redis:/data
      - ./srv/redis/redis.conf:/etc/redis/redis.conf:ro
    restart: always
