version: "2"
services:
  nginx:
    container_name: nginx
    image: library/nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./srv/www/default/:/usr/share/nginx/html/
      - ./srv/www/:/www/
      - ./srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./srv/nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      #- ./srv/nginx/certificate/214888618570699.pem:/etc/nginx/server.pem:ro
      #- ./srv/nginx/certificate/214888618570699.key/:/etc/nginx/server.key:ro
    links:
      - fpm:__DOCKER_PHP_FPM__
    restart: always

  fpm:
    container_name: php
    image: alicfeng/php:fpm-7.2.13
    ports:
      - 9000:9000
    volumes:
      - ./srv/www/default/:/usr/share/nginx/html/
      - ./srv/www/:/www/
      #- /srv/docker/php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    links:
      - mysql:mysql
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./srv/mysql/config/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: samego
      MYSQL_USER: samego
      MYSQL_PASSWORD: samego
      MYSQL_DATABASE: samego
    restart: always
    
  redis:
    container_name: redis
    image: redis:4.0.12
    command: ["redis-server", "/etc/redis/redis.conf","--appendonly", "yes"]
    ports:
      - 6389:6379
    volumes:
      - ./data/redis:/data
      - ./srv/redis/redis.conf:/etc/redis/redis.conf:ro
    restart: always
